### ISSUE TITLE
CODE_OF_CONDUCT.md out of date

### ISSUE THREAD

**Issue by hzierer** [eclipse-tractusx/vas-country-risk-frontend#14]
found during QG4 Check #12

the current one can be found here: https://raw.githubusercontent.com/eclipse/.github/master/CODE_OF_CONDUCT.md

**Comment by fabiodmota** [comment]
updated on https://github.com/catenax-ng/tx-vas-country-risk-frontend/commit/ad13cc82fe6a7086126ecec5d6abbd82894300b2
