### ISSUE TITLE
README.md is missing the mention of used base image(s)

### ISSUE THREAD

**Issue by hzierer** [eclipse-tractusx/vas-country-risk-frontend#16]
found during QG4 Check #12 

According to [TRG4.02](https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-02) the README.md has to include a mention of used base images(s), like e.g. [BPDM](https://github.com/eclipse-tractusx/bpdm#container-images)

**Comment by fabiodmota** [comment]
fixed on https://github.com/catenax-ng/tx-vas-country-risk-frontend/commit/333361681b1335655a73fc6c245aae1d906fd857
